name: Tests

on:
  push:
    branches:
      - master
      - add-frontmatter
  pull_request:
    branches:
      - master
      - add-frontmatter

jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./test/test.sh --debug

  test-osx:
    name: Test OSX
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash ./test/test.sh --debug
